In [3]:
import pandas as pd
from io import StringIO

In [46]:
csv_data = '''A,B,C,D
              1,0,,2
              1,,3,4
              3,3,,3'''

csv_data2 = '''A,B,C,D
              1,,,2
              1,,3,4
              3,,,'''

In [47]:
df = pd.read_csv( StringIO(csv_data) )
df2 = pd.read_csv( StringIO(csv_data2) )

In [31]:
df

A    B    C  D
0  1  0.0  NaN  2
1  1  NaN  3.0  4
2  3  3.0  NaN  3

In [38]:
# The following function name `pandas.dropna()` is used to automatically remove
# rows/coloumns that contains any NULL/NaN values. By specifiying `axis` to be
# 0 or 1 we can determine which axis to look through in order to remove these.

In [39]:
df.dropna(axis = 1)

A  D
0  1  2
1  1  4
2  3  3

In [40]:
df.dropna( axis = 0 )

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [41]:
df.dropna(how="all")

A    B    C  D
0  1  0.0  NaN  2
1  1  NaN  3.0  4
2  3  3.0  NaN  3

In [68]:
# Drop rows that have valeus less than the thresh.
df2.dropna( thresh = 3 )

A   B    C    D
1  1 NaN  3.0  4.0

In [69]:
df

A    B    C  D
0  1  0.0  NaN  2
1  1  NaN  3.0  4
2  3  3.0  NaN  3

In [71]:
from sklearn.impute import SimpleImputer

In [74]:
imputer = SimpleImputer( missing_values = np.nan , strategy = "mean" )

In [76]:
imputer = imputer.fit( df.values ) 

In [79]:
imputed = imputer.transform(df.values)

In [82]:
imputer = pd.DataFrame( imputed )

In [83]:
imputer

0    1    2    3
0  1.0  0.0  3.0  2.0
1  1.0  1.5  3.0  4.0
2  3.0  3.0  3.0  3.0

In [84]:
df

A    B    C  D
0  1  0.0  NaN  2
1  1  NaN  3.0  4
2  3  3.0  NaN  3

In [98]:
df = pd.DataFrame( [ 
                   ['green',  'M',  10.1, 'class2'],
                   ['yellow', 'M',  9.2,  'class3'],
                   ['yellow', 'XL', 15.2, 'class3'],
                   ['red',    'L',  1.2,  'class1']] )

In [99]:
df.columns = ["Color", "Size", "Price", "label"]

In [100]:
size_mapping = {
                "M" : 0,
                "L" : 1,
                "XL": 2 }

In [101]:
df["Size"] = df["Size"].map( size_mapping )

In [119]:
invert = { v : k for k, v in size_mapping.items() }

In [121]:
label_map = { val : idx for idx, val in enumerate( np.unique( df["label"] ) ) }

In [122]:
label_map

{'class1': 0, 'class2': 1, 'class3': 2}

In [124]:
df["label"] = df["label"].map(label_map) 

In [126]:
df

Color  Size  Price  label
0   green     0   10.1      1
1  yellow     0    9.2      2
2  yellow     2   15.2      2
3     red     1    1.2      0

In [128]:
inverse_label = { val:idx for idx, val in label_map.items() }

In [129]:
inverse_label

{0: 'class1', 1: 'class2', 2: 'class3'}

In [131]:
df["label"] = df["label"].map(inverse_label)

In [133]:
df

Color  Size  Price   label
0   green     0   10.1  class2
1  yellow     0    9.2  class3
2  yellow     2   15.2  class3
3     red     1    1.2  class1

In [134]:
from sklearn.preprocessing import LabelEncoder

In [135]:
encoder = LabelEncoder()

In [137]:
y = encoder.fit_transform( df["label"] )

In [138]:
encoder.inverse_transform(y)

array(['class2', 'class3', 'class3', 'class1'], dtype=object)

In [147]:
X = df[["Color", "Size", "Price"]].values

In [148]:
color_encoder = LabelEncoder()

In [152]:
X[:, 0] = color_encoder.fit_transform( X[:, 0] )

In [156]:
X[:, 0]

array([0, 2, 2, 1], dtype=object)

In [159]:
(X[:, 0].reshape(-1,1))

array([[0],
       [2],
       [2],
       [1]], dtype=object)

In [161]:
from sklearn.preprocessing import OneHotEncoder

In [162]:
color_ohe = OneHotEncoder()

In [163]:
color_ohe.fit_transform( X[: , 0].reshape(-1,1)).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])